<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class CountrySeeder extends Seeder
{
    public static function labels()
    {
        return  [
            ['name' => 'Afganistan', 'iso_code' => 'AF', 'iso_code3' => 'AFG', 'phone_code' => '+93', 'currency' => 'AFN'],
            ['name' => 'Insulele Åland', 'iso_code' => 'AX', 'iso_code3' => 'ALA', 'phone_code' => '+358', 'currency' => 'EUR'],
            ['name' => 'Albania', 'iso_code' => 'AL', 'iso_code3' => 'ALB', 'phone_code' => '+355', 'currency' => 'ALL'],
            ['name' => 'Algeria', 'iso_code' => 'DZ', 'iso_code3' => 'DZA', 'phone_code' => '+213', 'currency' => 'DZD'],
            ['name' => 'Samoa Americană', 'iso_code' => 'AS', 'iso_code3' => 'ASM', 'phone_code' => '+1684', 'currency' => 'USD'],
            ['name' => 'Andorra', 'iso_code' => 'AD', 'iso_code3' => 'AND', 'phone_code' => '+376', 'currency' => 'EUR'],
            ['name' => 'Angola', 'iso_code' => 'AO', 'iso_code3' => 'AGO', 'phone_code' => '+244', 'currency' => 'AOA'],
            ['name' => 'Anguila', 'iso_code' => 'AI', 'iso_code3' => 'AIA', 'phone_code' => '+1264', 'currency' => 'XCD'],
            ['name' => 'Antarctica', 'iso_code' => 'AQ', 'iso_code3' => 'ATA', 'phone_code' => '', 'currency' => 'AUD'],
            ['name' => 'Antigua și Barbuda', 'iso_code' => 'AG', 'iso_code3' => 'ATG', 'phone_code' => '+1268', 'currency' => 'XCD'],
            ['name' => 'Argentina', 'iso_code' => 'AR', 'iso_code3' => 'ARG', 'phone_code' => '+54', 'currency' => 'ARS'],
            ['name' => 'Armenia', 'iso_code' => 'AM', 'iso_code3' => 'ARM', 'phone_code' => '+374', 'currency' => 'AMD'],
            ['name' => 'Aruba', 'iso_code' => 'AW', 'iso_code3' => 'ABW', 'phone_code' => '+297', 'currency' => 'AWG'],
            ['name' => 'Australia', 'iso_code' => 'AU', 'iso_code3' => 'AUS', 'phone_code' => '+61', 'currency' => 'AUD'],
            ['name' => 'Austria', 'iso_code' => 'AT', 'iso_code3' => 'AUT', 'phone_code' => '+43', 'currency' => 'EUR'],
            ['name' => 'Azerbaidjan', 'iso_code' => 'AZ', 'iso_code3' => 'AZE', 'phone_code' => '+994', 'currency' => 'AZN'],
            ['name' => 'Bahamas', 'iso_code' => 'BS', 'iso_code3' => 'BHS', 'phone_code' => '+1242', 'currency' => 'BSD'],
            ['name' => 'Bahrain', 'iso_code' => 'BH', 'iso_code3' => 'BHR', 'phone_code' => '+973', 'currency' => 'BHD'],
            ['name' => 'Bangladesh', 'iso_code' => 'BD', 'iso_code3' => 'BGD', 'phone_code' => '+880', 'currency' => 'BDT'],
            ['name' => 'Barbados', 'iso_code' => 'BB', 'iso_code3' => 'BRB', 'phone_code' => '+1246', 'currency' => 'BBD'],
            ['name' => 'Belarus', 'iso_code' => 'BY', 'iso_code3' => 'BLR', 'phone_code' => '+375', 'currency' => 'BYN'],
            ['name' => 'Belgia', 'iso_code' => 'BE', 'iso_code3' => 'BEL', 'phone_code' => '+32', 'currency' => 'EUR'],
            ['name' => 'Belize', 'iso_code' => 'BZ', 'iso_code3' => 'BLZ', 'phone_code' => '+501', 'currency' => 'BZD'],
            ['name' => 'Benin', 'iso_code' => 'BJ', 'iso_code3' => 'BEN', 'phone_code' => '+229', 'currency' => 'CDF'],
            ['name' => 'Bermuda', 'iso_code' => 'BM', 'iso_code3' => 'BMU', 'phone_code' => '+1441', 'currency' => 'BMD'],
            ['name' => 'Bhutan', 'iso_code' => 'BT', 'iso_code3' => 'BTN', 'phone_code' => '+975', 'currency' => 'BTN'],
            ['name' => 'Bolivia', 'iso_code' => 'BO', 'iso_code3' => 'BOL', 'phone_code' => '+591', 'currency' => 'BOB'],
            ['name' => 'Bosnia și Herțegovina', 'iso_code' => 'BA', 'iso_code3' => 'BIH', 'phone_code' => '+387', 'currency' => 'BAM'],
            ['name' => 'Botswana', 'iso_code' => 'BW', 'iso_code3' => 'BWA', 'phone_code' => '+267', 'currency' => 'BWP'],
            ['name' => 'Insula Bouvet', 'iso_code' => 'BV', 'iso_code3' => 'BVT', 'phone_code' => '', 'currency' => 'NOK'],
            ['name' => 'Brazilia', 'iso_code' => 'BR', 'iso_code3' => 'BRA', 'phone_code' => '+55', 'currency' => 'BRL'],
            ['name' => 'Teritoriul Britanic din Oceanul Indian', 'iso_code' => 'IO', 'iso_code3' => 'IOT', 'phone_code' => '+246', 'currency' => 'USD'],
            ['name' => 'Brunei Darussalam', 'iso_code' => 'BN', 'iso_code3' => 'BRN', 'phone_code' => '+673', 'currency' => 'BND'],
            ['name' => 'Bulgaria', 'iso_code' => 'BG', 'iso_code3' => 'BGR', 'phone_code' => '+359', 'currency' => 'BGN'],
            ['name' => 'Burkina Faso', 'iso_code' => 'BF', 'iso_code3' => 'BFA', 'phone_code' => '+226', 'currency' => 'BIF'],
            ['name' => 'Burundi', 'iso_code' => 'BI', 'iso_code3' => 'BDI', 'phone_code' => '+257', 'currency' => 'BIF'],
            ['name' => 'Cambodgia', 'iso_code' => 'KH', 'iso_code3' => 'KHM', 'phone_code' => '+855', 'currency' => 'KHR'],
            ['name' => 'Camerun', 'iso_code' => 'CM', 'iso_code3' => 'CMR', 'phone_code' => '+237', 'currency' => 'XAF'],
            ['name' => 'Canada', 'iso_code' => 'CA', 'iso_code3' => 'CAN', 'phone_code' => '+1', 'currency' => 'CAD'],
            ['name' => 'Capul Verde', 'iso_code' => 'CV', 'iso_code3' => 'CPV', 'phone_code' => '+238', 'currency' => 'CVE'],
            ['name' => 'Insulele Cayman', 'iso_code' => 'KY', 'iso_code3' => 'CYM', 'phone_code' => '+1345', 'currency' => 'KYD'],
            ['name' => 'Republica Centrafricană', 'iso_code' => 'CF', 'iso_code3' => 'CAF', 'phone_code' => '+236', 'currency' => 'CAF'],
            ['name' => 'Ciad', 'iso_code' => 'TD', 'iso_code3' => 'TCD', 'phone_code' => '+235', 'currency' => 'CDF'],
            ['name' => 'Chile', 'iso_code' => 'CL', 'iso_code3' => 'CHL', 'phone_code' => '+56', 'currency' => 'CLP'],
            ['name' => 'China', 'iso_code' => 'CN', 'iso_code3' => 'CHN', 'phone_code' => '+86', 'currency' => 'CNY'],
            ['name' => 'Insula Christmas', 'iso_code' => 'CX', 'iso_code3' => 'CXR', 'phone_code' => '+61', 'currency' => 'AUD'],
            ['name' => 'Insulele Cocos (Keeling)', 'iso_code' => 'CC', 'iso_code3' => 'CCK', 'phone_code' => '+61', 'currency' => 'AUD'],
            ['name' => 'Columbia', 'iso_code' => 'CO', 'iso_code3' => 'COL', 'phone_code' => '+57', 'currency' => 'COP'],
            ['name' => 'Comore', 'iso_code' => 'KM', 'iso_code3' => 'COM', 'phone_code' => '+269', 'currency' => 'KMF'],
            ['name' => 'Congo', 'iso_code' => 'CG', 'iso_code3' => 'COG', 'phone_code' => '+242', 'currency' => 'CDF'],
            ['name' => 'Republica Democrată Congo', 'iso_code' => 'CD', 'iso_code3' => 'COD', 'phone_code' => '+243', 'currency' => 'CDF'],
            ['name' => 'Insulele Cook', 'iso_code' => 'CK', 'iso_code3' => 'COK', 'phone_code' => '+682', 'currency' => 'NZD'],
            ['name' => 'Costa Rica', 'iso_code' => 'CR', 'iso_code3' => 'CRI', 'phone_code' => '+506', 'currency' => 'CRC'],
            ['name' => 'Croația', 'iso_code' => 'HR', 'iso_code3' => 'HRV', 'phone_code' => '+385', 'currency' => 'HRK'],
            ['name' => 'Cuba', 'iso_code' => 'CU', 'iso_code3' => 'CUB', 'phone_code' => '+53', 'currency' => 'CUP'],
            ['name' => 'Cipru', 'iso_code' => 'CY', 'iso_code3' => 'CYP', 'phone_code' => '+357', 'currency' => 'CYP'],
            ['name' => 'Republica Cehă', 'iso_code' => 'CZ', 'iso_code3' => 'CZE', 'phone_code' => '+420', 'currency' => 'CZK'],
            ['name' => 'Danemarca', 'iso_code' => 'DK', 'iso_code3' => 'DNK', 'phone_code' => '+45', 'currency' => 'DKK'],
            ['name' => 'Djibouti', 'iso_code' => 'DJ', 'iso_code3' => 'DJI', 'phone_code' => '+253', 'currency' => 'DJF'],
            ['name' => 'Dominica', 'iso_code' => 'DM', 'iso_code3' => 'DMA', 'phone_code' => '+1767', 'currency' => 'XCD'],
            ['name' => 'Republica Dominicană', 'iso_code' => 'DO', 'iso_code3' => 'DOM', 'phone_code' => '+1809', 'currency' => 'DOP'],
            ['name' => 'Ecuador', 'iso_code' => 'EC', 'iso_code3' => 'ECU', 'phone_code' => '+593', 'currency' => 'USD'],
            ['name' => 'Egipt', 'iso_code' => 'EG', 'iso_code3' => 'EGY', 'phone_code' => '+20', 'currency' => 'EGP'],
            ['name' => 'El Salvador', 'iso_code' => 'SV', 'iso_code3' => 'SLV', 'phone_code' => '+503', 'currency' => 'SVC'],
            ['name' => 'Guineea Ecuatorială', 'iso_code' => 'GQ', 'iso_code3' => 'GNQ', 'phone_code' => '+240', 'currency' => 'GNF'],
            ['name' => 'Eritreea', 'iso_code' => 'ER', 'iso_code3' => 'ERI', 'phone_code' => '+291', 'currency' => 'ERN'],
            ['name' => 'Estonia', 'iso_code' => 'EE', 'iso_code3' => 'EST', 'phone_code' => '+372', 'currency' => 'EEK'],
            ['name' => 'Eswatini', 'iso_code' => 'SZ', 'iso_code3' => 'SWZ', 'phone_code' => '+268', 'currency' => 'SZL'],
            ['name' => 'Etiopia', 'iso_code' => 'ET', 'iso_code3' => 'ETH', 'phone_code' => '+251', 'currency' => 'ETB'],
            ['name' => 'Fidji', 'iso_code' => 'FJ', 'iso_code3' => 'FJI', 'phone_code' => '+679', 'currency' => 'FJD'],
            ['name' => 'Finlanda', 'iso_code' => 'FI', 'iso_code3' => 'FIN', 'phone_code' => '+358', 'currency' => 'FIM'],
            ['name' => 'Franța', 'iso_code' => 'FR', 'iso_code3' => 'FRA', 'phone_code' => '+33', 'currency' => 'EUR'],
            ['name' => 'Gabon', 'iso_code' => 'GA', 'iso_code3' => 'GAB', 'phone_code' => '+241', 'currency' => 'GAB'],
            ['name' => 'Gambia', 'iso_code' => 'GM', 'iso_code3' => 'GMB', 'phone_code' => '+220', 'currency' => 'GMD'],
            ['name' => 'Georgia', 'iso_code' => 'GE', 'iso_code3' => 'GEO', 'phone_code' => '+995', 'currency' => 'GEL'],
            ['name' => 'Germania', 'iso_code' => 'DE', 'iso_code3' => 'DEU', 'phone_code' => '+49', 'currency' => 'EUR'],
            ['name' => 'Ghana', 'iso_code' => 'GH', 'iso_code3' => 'GHA', 'phone_code' => '+233', 'currency' => 'GHS'],
            ['name' => 'Gibraltar', 'iso_code' => 'GI', 'iso_code3' => 'GIB', 'phone_code' => '+350', 'currency' => 'GIP'],
            ['name' => 'Grecia', 'iso_code' => 'GR', 'iso_code3' => 'GRC', 'phone_code' => '+30', 'currency' => 'EUR'],
            ['name' => 'Grenada', 'iso_code' => 'GD', 'iso_code3' => 'GRD', 'phone_code' => '+1473', 'currency' => 'GRD'],
            ['name' => 'Guadelupa', 'iso_code' => 'GP', 'iso_code3' => 'GLP', 'phone_code' => '+590', 'currency' => 'EUR'],
            ['name' => 'Guam', 'iso_code' => 'GU', 'iso_code3' => 'GUM', 'phone_code' => '+1671', 'currency' => 'USD'],
            ['name' => 'Guatemala', 'iso_code' => 'GT', 'iso_code3' => 'GTM', 'phone_code' => '+502', 'currency' => 'GTQ'],
            ['name' => 'Guineea', 'iso_code' => 'GN', 'iso_code3' => 'GIN', 'phone_code' => '+224', 'currency' => 'GNF'],
            ['name' => 'Guineea-Bisau', 'iso_code' => 'GW', 'iso_code3' => 'GNB', 'phone_code' => '+245', 'currency' => 'GNF'],
            ['name' => 'Guyana', 'iso_code' => 'GY', 'iso_code3' => 'GUY', 'phone_code' => '+592', 'currency' => 'GYD'],
            ['name' => 'Haiti', 'iso_code' => 'HT', 'iso_code3' => 'HTI', 'phone_code' => '+509', 'currency' => 'HTG'],
            ['name' => 'Honduras', 'iso_code' => 'HN', 'iso_code3' => 'HND', 'phone_code' => '+504', 'currency' => 'HNL'],
            ['name' => 'Hong Kong', 'iso_code' => 'HK', 'iso_code3' => 'HKG', 'phone_code' => '+852', 'currency' => 'HKD'],
            ['name' => 'Ungaria', 'iso_code' => 'HU', 'iso_code3' => 'HUN', 'phone_code' => '+36', 'currency' => 'HUF'],
            ['name' => 'Islanda', 'iso_code' => 'IS', 'iso_code3' => 'ISL', 'phone_code' => '+354', 'currency' => 'ISK'],
            ['name' => 'India', 'iso_code' => 'IN', 'iso_code3' => 'IND', 'phone_code' => '+91', 'currency' => 'INR'],
            ['name' => 'Indonezia', 'iso_code' => 'ID', 'iso_code3' => 'IDN', 'phone_code' => '+62', 'currency' => 'IDR'],
            ['name' => 'Irak', 'iso_code' => 'IQ', 'iso_code3' => 'IRQ', 'phone_code' => '+964', 'currency' => 'IQD'],
            ['name' => 'Irlanda', 'iso_code' => 'IE', 'iso_code3' => 'IRL', 'phone_code' => '+353', 'currency' => 'EUR'],
            ['name' => 'Isle of Man', 'iso_code' => 'IM', 'iso_code3' => 'IMN', 'phone_code' => '+44', 'currency' => 'GBP'],
            ['name' => 'Israel', 'iso_code' => 'IL', 'iso_code3' => 'ISR', 'phone_code' => '+972', 'currency' => 'ILS'],
            ['name' => 'Italia', 'iso_code' => 'IT', 'iso_code3' => 'ITA', 'phone_code' => '+39', 'currency' => 'EUR'],
            ['name' => 'Jamaica', 'iso_code' => 'JM', 'iso_code3' => 'JAM', 'phone_code' => '+1-876', 'currency' => 'JMD'],
            ['name' => 'Japonia', 'iso_code' => 'JP', 'iso_code3' => 'JPN', 'phone_code' => '+81', 'currency' => 'JPY'],
            ['name' => 'Yemen', 'iso_code' => 'YE', 'iso_code3' => 'YEM', 'phone_code' => '+967', 'currency' => 'YER'],
            ['name' => 'Jordan', 'iso_code' => 'JO', 'iso_code3' => 'JOR', 'phone_code' => '+962', 'currency' => 'JOD'],
            ['name' => 'Kazahstan', 'iso_code' => 'KZ', 'iso_code3' => 'KAZ', 'phone_code' => '+7', 'currency' => 'KZT'],
            ['name' => 'Kenya', 'iso_code' => 'KE', 'iso_code3' => 'KEN', 'phone_code' => '+254', 'currency' => 'KES'],
            ['name' => 'Kiribati', 'iso_code' => 'KI', 'iso_code3' => 'KIR', 'phone_code' => '+686', 'currency' => 'AUD'],
            ['name' => 'Kuwait', 'iso_code' => 'KW', 'iso_code3' => 'KWT', 'phone_code' => '+965', 'currency' => 'KWD'],
            ['name' => 'Kyrgyzstan', 'iso_code' => 'KG', 'iso_code3' => 'KGZ', 'phone_code' => '+996', 'currency' => 'KGS'],
            ['name' => 'Laos', 'iso_code' => 'LA', 'iso_code3' => 'LAO', 'phone_code' => '+856', 'currency' => 'LAK'],
            ['name' => 'Letonia', 'iso_code' => 'LV', 'iso_code3' => 'LVA', 'phone_code' => '+371', 'currency' => 'LVL'],
            ['name' => 'Liban', 'iso_code' => 'LB', 'iso_code3' => 'LBN', 'phone_code' => '+961', 'currency' => 'LBP'],
            ['name' => 'Liberia', 'iso_code' => 'LR', 'iso_code3' => 'LBR', 'phone_code' => '+231', 'currency' => 'LRD'],
            ['name' => 'Libia', 'iso_code' => 'LY', 'iso_code3' => 'LBY', 'phone_code' => '+218', 'currency' => 'LYD'],
            ['name' => 'Liechtenstein', 'iso_code' => 'LI', 'iso_code3' => 'LIE', 'phone_code' => '+423', 'currency' => 'CHF'],
            ['name' => 'Lituania', 'iso_code' => 'LT', 'iso_code3' => 'LTU', 'phone_code' => '+370', 'currency' => 'EUR'],
            ['name' => 'Luxemburg', 'iso_code' => 'LU', 'iso_code3' => 'LUX', 'phone_code' => '+352', 'currency' => 'EUR'],
            ['name' => 'Macau', 'iso_code' => 'MO', 'iso_code3' => 'MAC', 'phone_code' => '+853', 'currency' => 'MOP'],
            ['name' => 'Macedonia de Nord', 'iso_code' => 'MK', 'iso_code3' => 'MKD', 'phone_code' => '+389', 'currency' => 'MKD'],
            ['name' => 'Madagascar', 'iso_code' => 'MG', 'iso_code3' => 'MDG', 'phone_code' => '+261', 'currency' => 'MGA'],
            ['name' => 'Malawi', 'iso_code' => 'MW', 'iso_code3' => 'MWI', 'phone_code' => '+265', 'currency' => 'MWK'],
            ['name' => 'Maldiva', 'iso_code' => 'MV', 'iso_code3' => 'MDV', 'phone_code' => '+960', 'currency' => 'MVR'],
            ['name' => 'Mali', 'iso_code' => 'ML', 'iso_code3' => 'MLI', 'phone_code' => '+223', 'currency' => 'MRO'],
            ['name' => 'Malta', 'iso_code' => 'MT', 'iso_code3' => 'MLT', 'phone_code' => '+356', 'currency' => 'EUR'],
            ['name' => 'Mariana', 'iso_code' => 'MP', 'iso_code3' => 'MNP', 'phone_code' => '+1670', 'currency' => 'USD'],
            ['name' => 'Maroc', 'iso_code' => 'MA', 'iso_code3' => 'MAR', 'phone_code' => '+212', 'currency' => 'MAD'],
            ['name' => 'Mauritania', 'iso_code' => 'MR', 'iso_code3' => 'MRT', 'phone_code' => '+222', 'currency' => 'MRU'],
            ['name' => 'Mauritius', 'iso_code' => 'MU', 'iso_code3' => 'MUS', 'phone_code' => '+230', 'currency' => 'MUR'],
            ['name' => 'Mexic', 'iso_code' => 'MX', 'iso_code3' => 'MEX', 'phone_code' => '+52', 'currency' => 'MXN'],
            ['name' => 'Micronezia', 'iso_code' => 'FM', 'iso_code3' => 'FSM', 'phone_code' => '+691', 'currency' => 'USD'],
            ['name' => 'Moldova', 'iso_code' => 'MD', 'iso_code3' => 'MDA', 'phone_code' => '+373', 'currency' => 'MDL'],
            ['name' => 'Monaco', 'iso_code' => 'MC', 'iso_code3' => 'MCO', 'phone_code' => '+377', 'currency' => 'EUR'],
            ['name' => 'Mongolia', 'iso_code' => 'MN', 'iso_code3' => 'MNG', 'phone_code' => '+976', 'currency' => 'MNT'],
            ['name' => 'Mozambic', 'iso_code' => 'MZ', 'iso_code3' => 'MOZ', 'phone_code' => '+258', 'currency' => 'MZN'],
            ['name' => 'Myanmar', 'iso_code' => 'MM', 'iso_code3' => 'MMR', 'phone_code' => '+95', 'currency' => 'MMK'],
            ['name' => 'Namibia', 'iso_code' => 'NA', 'iso_code3' => 'NAM', 'phone_code' => '+264', 'currency' => 'NAD'],
            ['name' => 'Nauru', 'iso_code' => 'NR', 'iso_code3' => 'NRU', 'phone_code' => '+674', 'currency' => 'AUD'],
            ['name' => 'Nepal', 'iso_code' => 'NP', 'iso_code3' => 'NPL', 'phone_code' => '+977', 'currency' => 'NPR'],
            ['name' => 'Nicaragua', 'iso_code' => 'NI', 'iso_code3' => 'NIC', 'phone_code' => '+505', 'currency' => 'NIO'],
            ['name' => 'Niger', 'iso_code' => 'NE', 'iso_code3' => 'NER', 'phone_code' => '+227', 'currency' => 'XOF'],
            ['name' => 'Nigeria', 'iso_code' => 'NG', 'iso_code3' => 'NGA', 'phone_code' => '+234', 'currency' => 'NGN'],
            ['name' => 'Niue', 'iso_code' => 'NU', 'iso_code3' => 'NIU', 'phone_code' => '+683', 'currency' => 'NZD'],
            ['name' => 'Norvegia', 'iso_code' => 'NO', 'iso_code3' => 'NOR', 'phone_code' => '+47', 'currency' => 'NOK'],
            ['name' => 'Noua Zeelandă', 'iso_code' => 'NZ', 'iso_code3' => 'NZL', 'phone_code' => '+64', 'currency' => 'NZD'],
            ['name' => 'Olanda', 'iso_code' => 'NL', 'iso_code3' => 'NLD', 'phone_code' => '+31', 'currency' => 'EUR'],
            ['name' => 'Oman', 'iso_code' => 'OM', 'iso_code3' => 'OMN', 'phone_code' => '+968', 'currency' => 'OMR'],
            ['name' => 'Pacu', 'iso_code' => 'PA', 'iso_code3' => 'PAN', 'phone_code' => '+507', 'currency' => 'PAB'],
            ['name' => 'Palau', 'iso_code' => 'PW', 'iso_code3' => 'PLW', 'phone_code' => '+680', 'currency' => 'USD'],
            ['name' => 'Panama', 'iso_code' => 'PA', 'iso_code3' => 'PAN', 'phone_code' => '+507', 'currency' => 'PAB'],
            ['name' => 'Papua Noua Guinee', 'iso_code' => 'PG', 'iso_code3' => 'PNG', 'phone_code' => '+675', 'currency' => 'PGK'],
            ['name' => 'Paraguay', 'iso_code' => 'PY', 'iso_code3' => 'PRY', 'phone_code' => '+595', 'currency' => 'PYG'],
            ['name' => 'Peru', 'iso_code' => 'PE', 'iso_code3' => 'PER', 'phone_code' => '+51', 'currency' => 'PEN'],
            ['name' => 'Polonia', 'iso_code' => 'PL', 'iso_code3' => 'POL', 'phone_code' => '+48', 'currency' => 'PLN'],
            ['name' => 'Portugalia', 'iso_code' => 'PT', 'iso_code3' => 'PRT', 'phone_code' => '+351', 'currency' => 'EUR'],
            ['name' => 'Qatar', 'iso_code' => 'QA', 'iso_code3' => 'QAT', 'phone_code' => '+974', 'currency' => 'QAR'],
            ['name' => 'Réunion', 'iso_code' => 'RE', 'iso_code3' => 'REU', 'phone_code' => '+262', 'currency' => 'EUR'],
            ['name' => 'Romania', 'iso_code' => 'RO', 'iso_code3' => 'ROU', 'phone_code' => '+40', 'currency' => 'RON'],
            ['name' => 'Rusia', 'iso_code' => 'RU', 'iso_code3' => 'RUS', 'phone_code' => '+7', 'currency' => 'RUB'],
            ['name' => 'Rwanda', 'iso_code' => 'RW', 'iso_code3' => 'RWA', 'phone_code' => '+250', 'currency' => 'RWF'],
            ['name' => 'Samoa', 'iso_code' => 'WS', 'iso_code3' => 'WSM', 'phone_code' => '+685', 'currency' => 'WST'],
            ['name' => 'San Marino', 'iso_code' => 'SM', 'iso_code3' => 'SMR', 'phone_code' => '+378', 'currency' => 'EUR'],
            ['name' => 'Sao Tome si Principe', 'iso_code' => 'ST', 'iso_code3' => 'STP', 'phone_code' => '+239', 'currency' => 'STN'],
            ['name' => 'Senegal', 'iso_code' => 'SN', 'iso_code3' => 'SEN', 'phone_code' => '+221', 'currency' => 'CFA'],
            ['name' => 'Serbia', 'iso_code' => 'RS', 'iso_code3' => 'SRB', 'phone_code' => '+381', 'currency' => 'RSD'],
            ['name' => 'Seychelles', 'iso_code' => 'SC', 'iso_code3' => 'SYC', 'phone_code' => '+248', 'currency' => 'SCR'],
            ['name' => 'Sierra Leone', 'iso_code' => 'SL', 'iso_code3' => 'SLE', 'phone_code' => '+232', 'currency' => 'SLL'],
            ['name' => 'Singapore', 'iso_code' => 'SG', 'iso_code3' => 'SGP', 'phone_code' => '+65', 'currency' => 'SGD'],
            ['name' => 'Sint Maarten', 'iso_code' => 'SX', 'iso_code3' => 'SXM', 'phone_code' => '+1-721', 'currency' => 'ANG'],
            ['name' => 'Siria', 'iso_code' => 'SY', 'iso_code3' => 'SYR', 'phone_code' => '+963', 'currency' => 'SYP'],
            ['name' => 'Singapore', 'iso_code' => 'SG', 'iso_code3' => 'SGP', 'phone_code' => '+65', 'currency' => 'SGD'],
            ['name' => 'Slovacia', 'iso_code' => 'SK', 'iso_code3' => 'SVK', 'phone_code' => '+421', 'currency' => 'EUR'],
            ['name' => 'Slovenia', 'iso_code' => 'SI', 'iso_code3' => 'SVN', 'phone_code' => '+386', 'currency' => 'EUR'],
            ['name' => 'Solomon Islands', 'iso_code' => 'SB', 'iso_code3' => 'SLB', 'phone_code' => '+677', 'currency' => 'SBD'],
            ['name' => 'Somalia', 'iso_code' => 'SO', 'iso_code3' => 'SOM', 'phone_code' => '+252', 'currency' => 'SOS'],
            ['name' => 'South Africa', 'iso_code' => 'ZA', 'iso_code3' => 'ZAF', 'phone_code' => '+27', 'currency' => 'ZAR'],
            ['name' => 'South Sudan', 'iso_code' => 'SS', 'iso_code3' => 'SSD', 'phone_code' => '+211', 'currency' => 'SSP'],
            ['name' => 'Spain', 'iso_code' => 'ES', 'iso_code3' => 'ESP', 'phone_code' => '+34', 'currency' => 'EUR'],
            ['name' => 'Sri Lanka', 'iso_code' => 'LK', 'iso_code3' => 'LKA', 'phone_code' => '+94', 'currency' => 'LKR'],
            ['name' => 'Sudan', 'iso_code' => 'SD', 'iso_code3' => 'SDN', 'phone_code' => '+249', 'currency' => 'SDG'],
            ['name' => 'Suriname', 'iso_code' => 'SR', 'iso_code3' => 'SUR', 'phone_code' => '+597', 'currency' => 'SRD'],
            ['name' => 'Sweden', 'iso_code' => 'SE', 'iso_code3' => 'SWE', 'phone_code' => '+46', 'currency' => 'SEK'],
            ['name' => 'Switzerland', 'iso_code' => 'CH', 'iso_code3' => 'CHE', 'phone_code' => '+41', 'currency' => 'CHF'],
            ['name' => 'Syria', 'iso_code' => 'SY', 'iso_code3' => 'SYR', 'phone_code' => '+963', 'currency' => 'SYP'],
            ['name' => 'Taiwan', 'iso_code' => 'TW', 'iso_code3' => 'TWN', 'phone_code' => '+886', 'currency' => 'TWD'],
            ['name' => 'Tajikistan', 'iso_code' => 'TJ', 'iso_code3' => 'TJK', 'phone_code' => '+992', 'currency' => 'TJS'],
            ['name' => 'Tanzania', 'iso_code' => 'TZ', 'iso_code3' => 'TZA', 'phone_code' => '+255', 'currency' => 'TZS'],
            ['name' => 'Thailand', 'iso_code' => 'TH', 'iso_code3' => 'THA', 'phone_code' => '+66', 'currency' => 'THB'],
            ['name' => 'Togo', 'iso_code' => 'TG', 'iso_code3' => 'TGO', 'phone_code' => '+228', 'currency' => 'XOF'],
            ['name' => 'Tokelau', 'iso_code' => 'TK', 'iso_code3' => 'TKL', 'phone_code' => '+690', 'currency' => 'NZD'],
            ['name' => 'Tonga', 'iso_code' => 'TO', 'iso_code3' => 'TON', 'phone_code' => '+676', 'currency' => 'TOP'],
            ['name' => 'Trinidad and Tobago', 'iso_code' => 'TT', 'iso_code3' => 'TTO', 'phone_code' => '+1-868', 'currency' => 'TTD'],
            ['name' => 'Tunisia', 'iso_code' => 'TN', 'iso_code3' => 'TUN', 'phone_code' => '+216', 'currency' => 'TND'],
            ['name' => 'Turkey', 'iso_code' => 'TR', 'iso_code3' => 'TUR', 'phone_code' => '+90', 'currency' => 'TRY'],
            ['name' => 'Turkmenistan', 'iso_code' => 'TM', 'iso_code3' => 'TKM', 'phone_code' => '+993', 'currency' => 'TMT'],
            ['name' => 'Tuvalu', 'iso_code' => 'TV', 'iso_code3' => 'TUV', 'phone_code' => '+688', 'currency' => 'AUD'],
            ['name' => 'Uganda', 'iso_code' => 'UG', 'iso_code3' => 'UGA', 'phone_code' => '+256', 'currency' => 'UGX'],
            ['name' => 'Ukraine', 'iso_code' => 'UA', 'iso_code3' => 'UKR', 'phone_code' => '+380', 'currency' => 'UAH'],
            ['name' => 'United Arab Emirates', 'iso_code' => 'AE', 'iso_code3' => 'ARE', 'phone_code' => '+971', 'currency' => 'AED'],
            ['name' => 'United Kingdom', 'iso_code' => 'GB', 'iso_code3' => 'GBR', 'phone_code' => '+44', 'currency' => 'GBP'],
            ['name' => 'United States', 'iso_code' => 'US', 'iso_code3' => 'USA', 'phone_code' => '+1', 'currency' => 'USD'],
            ['name' => 'Uruguay', 'iso_code' => 'UY', 'iso_code3' => 'URY', 'phone_code' => '+598', 'currency' => 'UYU'],
            ['name' => 'Uzbekistan', 'iso_code' => 'UZ', 'iso_code3' => 'UZB', 'phone_code' => '+998', 'currency' => 'UZS'],
            ['name' => 'Vanuatu', 'iso_code' => 'VU', 'iso_code3' => 'VUT', 'phone_code' => '+678', 'currency' => 'VUV'],
            ['name' => 'Vatican City', 'iso_code' => 'VA', 'iso_code3' => 'VAT', 'phone_code' => '+39-06', 'currency' => 'EUR'],
            ['name' => 'Venezuela', 'iso_code' => 'VE', 'iso_code3' => 'VEN', 'phone_code' => '+58', 'currency' => 'VEF'],
            ['name' => 'Vietnam', 'iso_code' => 'VN', 'iso_code3' => 'VNM', 'phone_code' => '+84', 'currency' => 'VND'],
            ['name' => 'Wallis and Futuna', 'iso_code' => 'WF', 'iso_code3' => 'WLF', 'phone_code' => '+681', 'currency' => 'XPF'],
            ['name' => 'Western Sahara', 'iso_code' => 'EH', 'iso_code3' => 'ESH', 'phone_code' => '+212', 'currency' => 'MAD'],
            ['name' => 'Yemen', 'iso_code' => 'YE', 'iso_code3' => 'YEM', 'phone_code' => '+967', 'currency' => 'YER'],
            ['name' => 'Zambia', 'iso_code' => 'ZM', 'iso_code3' => 'ZMB', 'phone_code' => '+260', 'currency' => 'ZMW'],
            ['name' => 'Zimbabwe', 'iso_code' => 'ZW', 'iso_code3' => 'ZWE', 'phone_code' => '+263', 'currency' => 'ZWL'],

        ];
    }
    public function run(): void
    {
        DB::table('countries')->insert(self::labels());
    }
}